workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      android:
        build_type: release
      java: "17"
    scripts:
      - name: Set Android SDK path
        script: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
      - name: Build Android
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/**/*.apk

  android-debug:
    name: Android Debug
    max_build_duration: 60
    environment:
      android:
        build_type: debug
      java: "17"
    scripts:
      - name: Set Android SDK path
        script: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
      - name: Build Android
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
